### ISSUE TITLE
decryption fail or Incorrect mac leads to FATAL ERROR - BAD_RECORD_MAC

### ISSUE THREAD

**Issue by thiyaneshece** [gesslerpd/pyopenssl-psk#3]
i am using this library for PSK_AES128_GCM_SHA256 cipher suite between server uses openssl library and client uses py_openssl_psk library.

During the handshake process, i m getting an error that due to decryption fail or incorrect mac leads to ALERT FATAL - BAD RECORD_MAC. 

I have attached the client file for reference. Can you please let me know, what goes wrong in incorrect mac. 

Env - Windows 10 , py 3.7 and openssl - 1.1.1
[script_to_report.txt](https://github.com/gesslerpd/pyopenssl-psk/files/5174809/script_to_report.txt)

**Comment by gesslerpd** [comment]
Your PSK callback appears to be returning various byte ascii strings that are in hex form, so I wanted to point out that you could convert the hex ascii strings to raw hex bytes using `bytes.fromhex('CC75075075')` on Python3, unsure if that was your intent.

Also found this stack exchange answer that talks about the various causes for bad_record_mac. https://security.stackexchange.com/a/39846

**Comment by thiyaneshece** [comment]
@gesslerpd - Yes, it worked for me , now i could see the successful handshake followed by exchange of application data between client and server. Thanks for pointing out the issue.

**Comment by gesslerpd** [comment]
You're welcome! Some configs for PSK use a hex representation because it's easier to include in plaintext, but since we are in python we use whatever the bytes object contains literally without any transformation.
