### ISSUE TITLE
AttributeError :__Enter__ error is throwed in pyopenssl lib 20.01 

### ISSUE THREAD

**Issue by thiyaneshece** [gesslerpd/pyopenssl-psk#6]
When creating a secure websocket connection(wss) using websocket create_connection() api call in pyopenssl - openssl/ssl.py (20.0.1), **AttributeError: __enter__** error is thrown.

Websocket call flow : websocket.create_connection() -> websock.connect->handshake() -> send(sock, header_str) -> sock.send(data)

**Surprisingly,** when using 19.1.0 of pyopenssl version, there was no such error observed.

Between these 2 versions, send() method in SSL.py file does not have any changes. surprised to see the results when i execute the test case. 
@gesslerpd : Do you have any comments on this ? It would be really grateful if you have any suggestions to fix the issue .

`with _from_buffer(buf) as data:             

    if len(buf) > 2147483647:                 

        raise ValueError("Cannot send more than 2**31-1 bytes at once.")

    result = _lib.SSL_write(self._ssl, data, len(data))

    self._raise_ssl_error(self._ssl, result)

    return `result`

Complete error flow is given below : 
line 514, in create_connection
    websock.connect(url, **options)
line 226, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
line 76, in handshake
    send(sock, header_str)
line 157, in send
    return _send()
line 139, in _send
    return sock.send(data)
line 1644, in send
    with _from_buffer(buf) as data:
AttributeError: __enter__

**Comment by gesslerpd** [comment]
Seems like this issue isn't related to the patching done by `openssl_psk` and is likely an issue in pyopenssl itself.

`__enter__` function has to do with python context managers and pyopenssl recently started using the `cffi` buffer api directly.

Running the `pip install cffi -U` command in your python environment should get the latest version of that api with context manager support.

**Comment by thiyaneshece** [comment]
@gesslerpd Thanks for your feedback, worked like a gem.
