### ISSUE TITLE
The hint type cannot be bytes

### ISSUE THREAD

**Issue by dustinglion** [gesslerpd/pyopenssl-psk#8]
I need to send hint b'\x01\x00\x00\x01', but the callback return hint b'x01'.
I find that OpenSSL decode \x00 as an end of string, is there any Solution?

**Comment by gesslerpd** [comment]
![image](https://user-images.githubusercontent.com/11217948/218638568-152f1b41-dc9b-4d50-81c6-2d08ab6b2458.png)

This is an excerpt from the OpenSSL [documentation](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_use_psk_identity_hint.html#DESCRIPTION), the PSK hints are cstring pointers (nul-terminated) so unfortunately the python bytestrings are only processed up to the first nul-byte by OpenSSL itself.

**Comment by dustinglion** [comment]
Thanks, I'm trying to override the OpenSSL C lib

**Comment by dustinglion** [comment]
> Thanks
